### PR TITLE
Define well-known HTTP status for unprocessable entity

### PR DESCRIPTION
**Pull request by curban111**

### CODE REVIEW

**Review by Pascal-Thiel — APPROVED** [review]
Looks fine to me. I approve the request.

**Comment by jmichler** [comment]
So as a result it is the responsibility of the caller to manually initiate a clarification process? Then at least it should be mandatory to provide a clear error message together with the status code?
Does it really make sense to give the responsibility to the caller? Wouldn't it be more appropriate to have a "clearing process" on the receiver side of the message?

**Comment by curban111** [comment]
It would be better if the recipient of the message took care of the problem. But as in most other error cases, the caller will have to take care of the clarification. Previous experience has shown that most ERP systems do not transmit any information about the rejected transaction update to the relevant departments in such cases. Since clearing processes are usually complicated to establish, we have so far refrained from doing so. **However, this does not mean that such a process will be implemented in a later version.**

I'll expand the description of the new state to include a meaningful message to be sent in response.

**Comment by jmichler** [comment]
The clearing process will be needed in any case, won't it? Question is only on which side the process will be established... But anyway, we can do it like this "for now" - on our side HTTP-Error will have to be handled by IT for now

**Comment by curban111** [comment]
OK, I'm with you there. Let's put the issue "clearing process" on the working group's agenda when the time comes.

I have adjusted the description. If @Pascal-Thiel  agrees to the additional change, we'll merge the branch.

**Pull request merged**
